<?php
/**
 * Plugin Name: Events Manager TimeZones
 * Description: Uses Moment Timezone to add JavaScript replacement of times and dates generated by Events Manager
 * Version: 3.0.0
 * Author: Jemima Kingsley
 * Author URI: http://websitedepartment.co.uk/
 * License: GNU General Public License v3.0
 * License URI: http://www.gnu.org/licenses/gpl-3.0.html
 */


function emtz_adding_scripts() {

    wp_register_script( 'js-cookie',
                            plugin_dir_url( __FILE__ ) . 'js/js.cookie.js',
                            array ( ),
                            1.0,
                            true);
    wp_register_script( 'bp-moment',
                            plugin_dir_url( __FILE__ ) . 'js/moment.js',
                            array ( ),
                            2.18,
                            true);
    wp_register_script( 'moment-timezone-with-data-2012-2022',
                            plugin_dir_url( __FILE__ ) . 'js/moment-timezone-with-data-2012-2022.js',
                            array ( 'bp-moment' ),
                            1.0,
                            true);
    wp_register_script( 'events-manager-timezones',
                            plugin_dir_url( __FILE__ ) . 'js/events-manager-timezone.js',
                            array ( 'jquery',
                                    'bp-moment',
                                    'moment-timezone-with-data-2012-2022',
                                    'js-cookie',
                                    'jquery-replacetext-plugin' ),
                            1.0,
                            true);

    wp_enqueue_script('events-manager-timezones');
}


add_action( 'bp_enqueue_scripts', 'emtz_adding_scripts' );
