<?php
/**
 * Plugin Name: Events Manager TimeZones
 * Description: Uses Moment Timezone to add JavaScript replacement of times and dates generated by Events Manager
 * Version: 1.0.0
 * Author: Jemima Kingsley
 * Author URI: http://websitedepartment.co.uk/
 * License: GNU General Public License v3.0
 * License URI: http://www.gnu.org/licenses/gpl-3.0.html
 */

global $Events_Manager_TimeZones;

$Events_Manager_TimeZones = new Events_Manager_TimeZones;
class Events_Manager_TimeZones {
    private $textdomain = "Events_Manager_TimeZones";
    private $required_plugins = array('events-manager');
    function have_required_plugins() {
        if (empty($this->required_plugins))
            return true;
        $active_plugins = (array) get_option('active_plugins', array());
        if (is_multisite()) {
            $active_plugins = array_merge($active_plugins, get_site_option('active_sitewide_plugins', array()));
        }
        foreach ($this->required_plugins as $key => $required) {
            $required = (!is_numeric($key)) ? "{$key}/{$required}.php" : "{$required}/{$required}.php";
            if (!in_array($required, $active_plugins) && !array_key_exists($required, $active_plugins))
                return false;
        }
        return true;
    }
    function __construct() {
        if (!$this->have_required_plugins())
            return;
        load_plugin_textdomain($this->textdomain, false, dirname(plugin_basename(__FILE__)) . '/languages');

        wp_enqueue_script( 'js-cookie',
                            plugin_dir_url( __FILE__ ) . 'js/js.cookie.js',
                            array ( ),
                            1.0,
                            true);

        // We call it bp-moment because that's what BuddyPress calls it. If we don't use the same name, they fight each other and timezones don't work in BuddyPress.
        wp_enqueue_script( 'bp-moment',
                            plugin_dir_url( __FILE__ ) . 'js/moment.js',
                            array ( ),
                            2.18,
                            true);

        wp_enqueue_script( 'moment-timezone-with-data-2012-2022',
                            plugin_dir_url( __FILE__ ) . 'js/moment-timezone-with-data-2012-2022.js',
                            array ( 'bp-moment' ),
                            1.0,
                            true);

        wp_enqueue_script( 'events-manager-timezones',
                            plugin_dir_url( __FILE__ ) . 'js/events-manager-timezone.js',
                            array ( 'jquery', 'bp-moment', 'moment-timezone-with-data-2012-2022', 'js-cookie' ),
                            1.0,
                            true);

        do_action( 'bp_enqueue_scripts', 'events-manager-timezones' );
    }
}
